### ISSUE TITLE
Full Stack Capstone Kanban Board

### ISSUE THREAD

**Issue by ikennarichard** [ikennarichard/appointment-app-front-end#10]
For this project we created a Kanban board for the Full stack capstone project, for this project we 4 in our team.
- [Backend Kanban](https://github.com/users/mnaibei/projects/7).
     - <img width="1236" alt="Screenshot 2023-08-16 at 17 10 43" src="https://github.com/ikennarichard/appointment-app-front-end/assets/69506217/580d86a2-ef24-4103-b03c-5f198b0ec6e2">
   

- [Frontend Kanban](https://github.com/ikennarichard/appointment-app-front-end/projects/1)
    -  <img width="1236" alt="Screenshot 2023-08-16 at 17 14 13" src="https://github.com/ikennarichard/appointment-app-front-end/assets/69506217/0507a8b6-68ac-45c3-93a7-37822e1077e4">

**Comment by Meltrust** [comment]
Hi @belalgamal46,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been assigned, have descriptions, and have been pointed fairly ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
